### ISSUE TITLE
jenkins-ci-ARM-ubuntu-18-04 cannot pass unit test

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#1287]
https://github.com/kata-containers/runtime/pull/1281 http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/180/consoleText
```
--- FAIL: TestEnvGetEnvInfoSetsCPUType (0.03s)
    assertions.go:239: 
                          
	Error Trace:	kata-env_generic_test.go:48
        
	            	
			kata-env_arm64_test.go:98
        
	Error:      	Not equal: 
        
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/719236972/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/719236972/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/719236972/image"}, Kernel:main.KernelInfo{Path:"/tmp/719236972/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/719236972/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/719236972/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/719236972/netmon", Debug:false, Enable:false}}
        
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/719236972/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/719236972/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/719236972/image"}, Kernel:main.KernelInfo{Path:"/tmp/719236972/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/719236972/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/719236972/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/719236972/netmon", Debug:false, Enable:false}}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -67,3 +67,3 @@
        
	            	   VMContainerCapable: (bool) true,
        
	            	-  SupportVSocks: (bool) false
        
	            	+  SupportVSocks: (bool) true
        
	            	  },
=== RUN   TestEnvGetMetaInfo
--- PASS: TestEnvGetMetaInfo (0.00s)
=== RUN   TestEnvGetHostInfo
time="2019-02-27T08:39:42+08:00" level=info msg="Unable to know if the system is running inside a VM" source=virtcontainers
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio network" name=vhost_net pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Kernel-based Virtual Machine" name=kvm pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio" name=vhost pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
--- FAIL: TestEnvGetHostInfo (0.00s)
    assertions.go:239: 
                          
	Error Trace:	kata-env_test.go:448
        
	Error:      	Not equal: 
        
	            	expected: main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}
        
	            	actual: main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -12,3 +12,3 @@
        
	            	  VMContainerCapable: (bool) true,
        
	            	- SupportVSocks: (bool) false
        
	            	+ SupportVSocks: (bool) true
        
	            	 }
=== RUN   TestEnvGetHostInfoNoProcCPUInfo
--- PASS: TestEnvGetHostInfoNoProcCPUInfo (0.00s)
=== RUN   TestEnvGetHostInfoNoOSRelease
--- PASS: TestEnvGetHostInfoNoOSRelease (0.00s)
=== RUN   TestEnvGetHostInfoNoProcVersion
--- PASS: TestEnvGetHostInfoNoProcVersion (0.00s)
=== RUN   TestEnvGetEnvInfo
time="2019-02-27T08:39:42+08:00" level=info msg="Unable to know if the system is running inside a VM" source=virtcontainers
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio" name=vhost pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio network" name=vhost_net pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Kernel-based Virtual Machine" name=kvm pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="Unable to know if the system is running inside a VM" source=virtcontainers
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio network" name=vhost_net pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Kernel-based Virtual Machine" name=kvm pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio" name=vhost pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
--- FAIL: TestEnvGetEnvInfo (0.04s)
    assertions.go:239: 
                          
	Error Trace:	kata-env_test.go:527
        
	Error:      	Not equal: 
        
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/712492863/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/712492863/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/712492863/image"}, Kernel:main.KernelInfo{Path:"/tmp/712492863/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/712492863/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/712492863/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/712492863/netmon", Debug:false, Enable:false}}
        
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/712492863/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/712492863/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/712492863/image"}, Kernel:main.KernelInfo{Path:"/tmp/712492863/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/712492863/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/712492863/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/712492863/netmon", Debug:false, Enable:false}}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -67,3 +67,3 @@
        
	            	   VMContainerCapable: (bool) true,
        
	            	-  SupportVSocks: (bool) false
        
	            	+  SupportVSocks: (bool) true
        
	            	  },
    assertions.go:239: 
                          
	Error Trace:	kata-env_test.go:527
        
	Error:      	Not equal: 
        
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/712492863/runtime.toml"}, Debug:true, Trace:true, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/712492863/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:true, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/712492863/image"}, Kernel:main.KernelInfo{Path:"/tmp/712492863/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/712492863/proxy", Debug:true}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/712492863/shim", Debug:true}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/712492863/netmon", Debug:false, Enable:false}}
        
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/712492863/runtime.toml"}, Debug:true, Trace:true, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/712492863/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:true, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/712492863/image"}, Kernel:main.KernelInfo{Path:"/tmp/712492863/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/712492863/proxy", Debug:true}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/712492863/shim", Debug:true}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/712492863/netmon", Debug:false, Enable:false}}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -67,3 +67,3 @@
        
	            	   VMContainerCapable: (bool) true,
        
	            	-  SupportVSocks: (bool) false
        
	            	+  SupportVSocks: (bool) true
        
	            	  },
=== RUN   TestEnvGetEnvInfoNoHypervisorVersion
time="2019-02-27T08:39:42+08:00" level=info msg="Unable to know if the system is running inside a VM" source=virtcontainers
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio" name=vhost pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Host kernel accelerator for virtio network" name=vhost_net pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
time="2019-02-27T08:39:42+08:00" level=info msg="kernel property found" arch=arm64 container=1 description="Kernel-based Virtual Machine" name=kvm pid=42980 sandbox=99999999-9999-9999-99999999999999999 source=runtime type=module
--- FAIL: TestEnvGetEnvInfoNoHypervisorVersion (0.02s)
    assertions.go:239: 
                          
	Error Trace:	kata-env_test.go:552
        
	Error:      	Not equal: 
        
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/675713938/runtime.toml"}, Debug:true, Trace:true, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"<<unknown>>", Path:"/tmp/675713938/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:true, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/675713938/image"}, Kernel:main.KernelInfo{Path:"/tmp/675713938/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/675713938/proxy", Debug:true}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/675713938/shim", Debug:true}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/675713938/netmon", Debug:false, Enable:false}}
        
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.0", Commit:"0a611b9b87e138275a0f7c6c43a0af377ff2163c", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/675713938/runtime.toml"}, Debug:true, Trace:true, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build015849340/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"<<unknown>>", Path:"/tmp/675713938/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:true, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/675713938/image"}, Kernel:main.KernelInfo{Path:"/tmp/675713938/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/675713938/proxy", Debug:true}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/675713938/shim", Debug:true}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/675713938/netmon", Debug:false, Enable:false}}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -67,3 +67,3 @@
        
	            	   VMContainerCapable: (bool) true,
        
	            	-  SupportVSocks: (bool) false
        
	            	+  SupportVSocks: (bool) true
        
	            	  },
```

Also meet in:
https://github.com/kata-containers/runtime/pull/1286
http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/181/consoleText

**Comment by teawater** [comment]
@Pennyzct Maybe you can look at this issue.

**Comment by Pennyzct** [comment]
@teawater  Sorry for the delay, got sidetracked. thanks for the notification, and I'm working on this. :)

**Comment by teawater** [comment]
Now it failed in another place:
```
INFO: creating OCI bundle in /tmp/kata-runtime-944448708/bundle for tests to use
time="2019-03-02T10:14:34+08:00" level=debug msg="converting /tmp/kata-runtime-944448708/bundle/config.json" source=virtcontainers subsystem=oci
=== RUN   TestConsoleFromFile
--- PASS: TestConsoleFromFile (0.00s)
=== RUN   TestNewConsole
--- FAIL: TestNewConsole (0.00s)
    assertions.go:239: 
                          
	Error Trace:	console_test.go:28
        
	Error:      	Received unexpected error:
        
	            	open /dev/ptmx: no such device
        
	Messages:   	failed to create a new console: open /dev/ptmx: no such device
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xacb5fc]

goroutine 101 [running]:
testing.tRunner.func1(0x40003ce000)
	/usr/local/go/src/testing/testing.go:792 +0x30c
panic(0xc2e900, 0x1560890)
	/usr/local/go/src/runtime/panic.go:513 +0x18c
github.com/kata-containers/runtime/cli.(*Console).Close(0x0, 0x4000344f80, 0x2)
	/home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/runtime/cli/console.go:88 +0x44
panic(0xc2e900, 0x1560890)
	/usr/local/go/src/runtime/panic.go:513 +0x18c
github.com/kata-containers/runtime/cli.(*Console).Path(...)
	/home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/runtime/cli/console.go:73
github.com/kata-containers/runtime/cli.TestNewConsole(0x40003ce000)
	/home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/runtime/cli/console_test.go:31 +0xf0
testing.tRunner(0x40003ce000, 0xd89c98)
	/usr/local/go/src/testing/testing.go:827 +0xa8
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x2b0
FAIL	github.com/kata-containers/runtime/cli	1.682s
Makefile:532: recipe for target 'go-test' failed
make: *** [go-test] Error 1
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```
https://github.com/kata-containers/runtime/pull/1166
https://github.com/kata-containers/runtime/pull/1286

**Comment by Pennyzct** [comment]
@teawater I'm not sure why and where at the first place `/dev/ptmx` got deleted. And I have already rebooted ARM CI machine to bring it back. Let's see if it's repeatable. ;)

**Comment by grahamwhaley** [comment]
Ooh, occasionally we have had a PR that tried to do some enhancements with host side device mappings into the guests, or guest /dev/ cleanup, and that has iirc resulted in some host /dev being removed.... which is not a big problem for the one-shot cloud CI instances, but would be for the bare metal machines!
@devimc - do you know if we have had any of those types of PRs recently?

n.b. for the metrics CI this may not be such a big issue, as we have a Jenkins task that tries to reboot the machine after every PR build - so we may not have noticed it on the metrics CI slave.
