### ISSUE TITLE
s390x: Failed to build kata-runtime 1.6.3

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#1680]
Snap 1.6.3 won't be release for s390x

```
kata-runtime - version 1.6.3 (commit f42b791689d1f2aef7593428ad7c5093a2f26d29)

• architecture:
	Host: 
	golang: s390x
	Build: s390x

• golang:
	go version go1.10.4 linux/s390x

• hypervisors:
	Known: firecracker qemu
	Available for this architecture: qemu

• Summary:

	destination install path (DESTDIR) : /
	binary installation path (BINDIR) : /snap/kata-containers/current/usr/bin
	binaries to install :
	 - /snap/kata-containers/current/usr/bin/kata-runtime
	 - /snap/kata-containers/current/usr/bin/containerd-shim-kata-v2
	 - /snap/kata-containers/current/usr/libexec/kata-containers/kata-netmon
	 - /snap/kata-containers/current/usr/bin/data/kata-collect-data.sh
	configs to install (CONFIGS) :
	 - cli/config/configuration-qemu.toml
	install paths (CONFIG_PATHS) :
	 - /snap/kata-containers/current/usr/share/defaults/kata-containers/configuration-qemu.toml
	alternate config paths (SYSCONFIG_PATHS) : 
	 - /etc/kata-containers/configuration-qemu.toml
	default install path for qemu (CONFIG_PATH) : /snap/kata-containers/current/usr/share/defaults/kata-containers/configuration.toml
	default alternate config path (SYSCONFIG) : /etc/kata-containers/configuration.toml
	qemu hypervisor path (QEMUPATH) : /snap/kata-containers/current/usr/bin/qemu-system-s390x
	assets path (PKGDATADIR) : /snap/kata-containers/current/usr/share/kata-containers
	proxy+shim path (PKGLIBEXECDIR) : /snap/kata-containers/current/usr/libexec/kata-containers

     BUILD    /build/kata-containers/parts/runtime/build/go/src/github.com/kata-containers/runtime/kata-runtime
# github.com/kata-containers/runtime/virtcontainers
../virtcontainers/qemu_s390x.go:13:2: imported and not used: "time"
make: *** [/build/kata-containers/parts/runtime/build/go/src/github.com/kata-containers/runtime/kata-runtime] Error 2
Makefile:393: recipe for target '/build/kata-containers/parts/runtime/build/go/src/github.com/kata-containers/runtime/kata-runtime' failed
Failed to run 'override-build': Exit code was 2.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 265, in run
    self.build()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 254, in build
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 103, in run_build_command
    return self.backend.run(args, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 497, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-bionic-s390x', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": "https://launchpad.net/~kata-containers-dev/+snap/snap-next/+build/558667"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/kata-containers && linux64 snapcraft']' returned non-zero exit status 2
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=s390x SNAPBUILD-558667
Scanning for processes to kill in build SNAPBUILD-558667
```

cc @alicefr @tuan-hoang1

**Comment by tuan-hoang1** [comment]
Thanks for reporting. We are aware of this problem. Fix coming soon.

**Comment by alicefr** [comment]
@devimc against which branch or tag do we need to open the PR?

**Comment by devimc** [comment]
@tuan-hoang1 @alicefr thanks for fixing it.
btw 1.7.0 was released https://snapcraft.io/kata-containers
