### ISSUE TITLE
Runtime crash when virtiofsd is not executable

### ISSUE THREAD

**Issue by c3d** [kata-containers/runtime#2682]
# Description of problem

If the configuration file points to a `virtiofsd` that exists but is not executable, then the runtime crashes with a segmentation violation.

This is a variant of #2582.

# Expected result

Error message

# Actual result

Something like

```
Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x562180e63a48]
goroutine 7 [running]:
os.(*Process).wait(0x0, 0xc000000004, 0xc00035db50, 0x1)
  /usr/lib/golang/src/os/exec_unix.go:17 +0x28
os.(*Process).Wait(...)
  /usr/lib/golang/src/os/exec.go:125
github.com/kata-containers/runtime/virtcontainers.(*qemu).setupVirtiofsd.func1(0x562181bea460, 0xc00058a040, 0xc0001ca500, 0xc0002dc000)
  /home/ddd/go/src/github.com/kata-containers/runtime/virtcontainers/qemu.go:689 +0x4a5
created by github.com/kata-containers/runtime/virtcontainers.(*qemu).setupVirtiofsd
           /home/ddd/go/src/github.com/kata-containers/runtime/virtcontainers/qemu.go:682 +0x2d8
  Warning  FailedCreatePodSandBox  53s (x17 over 4m38s)  kubelet, muse  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: panic: runtime error: invalid memory address or nil
 pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55fdd99cea48]
```

**Comment by fidencio** [comment]
@c3d, a few comments:

1. What does happen when you run your code with the binary removed?
2. Your commit message is duplicated, please remove the duplicated part;
3. As your PR goes against runtime and the issue is also filled against the runtime, you can use only `Fixes: #NNN` instead of `Fixes: kata-containers#NNN`

**Comment by fidencio** [comment]
Argh, let me move my comments to the PR :-)
