### ISSUE TITLE
Attaching vhost-user network device is broken

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#446]
This results in a panic:
```ror msg="fatal error" command=create name=kata-runtime panic="interface conversion: drivers.VhostUserNetDevice is not api.VhostUserDevice: missing method Attrs" pid=31
ror msg="--- contention:" command=create name=kata-runtime pid=31423 source=runtime
ror msg="cycles/second=1800003474" command=create name=kata-runtime pid=31423 source=runtime
ror msg="goroutine 1 [running, locked to thread]:" command=create name=kata-runtime pid=31423 source=runtime
ror msg="runtime/pprof.writeGoroutineStacks(0xc07c80, 0xc4200c9260, 0xc420354000, 0x1000)" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/local/go/src/runtime/pprof/pprof.go:650 +0xa7" command=create name=kata-runtime pid=31423 source=runtime
ror msg="runtime/pprof.writeGoroutine(0xc07c80, 0xc4200c9260, 0x2, 0x0, 0x0)" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/local/go/src/runtime/pprof/pprof.go:639 +0x44" command=create name=kata-runtime pid=31423 source=runtime
ror msg="runtime/pprof.(*Profile).WriteTo(0x115b540, 0xc07c80, 0xc4200c9260, 0x2, 0x0, 0x0)" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/local/go/src/runtime/pprof/pprof.go:310 +0x3e4" command=create name=kata-runtime pid=31423 source=runtime
ror msg="main.backtrace()" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/go/src/github.com/kata-containers/runtime/cli/signals.go:51 +0xb5" command=create name=kata-runtime pid=31423 source=runtime
ror msg="main.die()" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/go/src/github.com/kata-containers/runtime/cli/signals.go:88 +0x26" command=create name=kata-runtime pid=31423 source=runtime
ror msg="main.handlePanic()" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/go/src/github.com/kata-containers/runtime/cli/signals.go:39 +0x145" command=create name=kata-runtime pid=31423 source=runtime
ror msg="panic(0xab3a40, 0xc42007e640)" command=create name=kata-runtime pid=31423 source=runtime
ror msg="\t/usr/src/packages/BUILD/local/go/src/runtime/panic.go:502 +0x229" command=create name=kata-runtime pid=31423 source=runtime
ror msg="github.com/kata-containers/runtime/virtcontainers.(*qemu).addDevice(0xc4202da380, 0xae0380, 0xc420114fd0, 0x8, 0x10, 0x0)" command=create name=kata-runtime p$
ror msg="\t/usr/src/packages/BUILD/go/src/github.com/kata-containers/runtime/virtcontainers/qemu.go:900 +0x747" command=create name=kata-runtime pid=31423 source=runt$
ror msg="github.com/kata-containers/runtime/virtcontainers.(*VhostUserEndpoint).Attach(0xc420196380, 0xc16bc0, 0xc4202da380, 0xc420297d98, 0x42b009)" command=create n
```

**Comment by jodh-intel** [comment]
Ouch. Atleast we caught the panic though ;)

**Comment by jodh-intel** [comment]
Could you confirm you got a "fatal error" log message just before the panic btw?

**Comment by amshinde** [comment]
@jodh-intel yes, I did get a "fatal error" log message.

**Comment by jodh-intel** [comment]
Thanks @amshinde. Since the CI checks for fatal errors, this implies we don't have a test for vhost user net? A quick look suggests we haven't but could you confirm and raise a tests issue so we can add one?

**Comment by amshinde** [comment]
@jodh-intel Yes we dont. I had created an issue yesterday for an integration test to check the vhost-user flow end to end, but I think this part can be tested with a unit test. I'll create an issue for it.

**Comment by jodh-intel** [comment]
Thanks @amshinde.
