### ISSUE TITLE
TestRunContainerDeleteFail timed out on ubuntu 16.04 CI job

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#554]
Unit test timing out:

http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-PR/393/console
```
=== RUN   TestRunContainerDeleteFail
coverage: 81.3% of statements
panic: test timed out after 10s

goroutine 365 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0x146
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc42030a000, 0x101ba11, 0x1a, 0x1044660, 0xc42029db01)
	/usr/local/go/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc42030a000)
	/usr/local/go/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc42030a000, 0xc42029dce0)
	/usr/local/go/src/testing/testing.go:777 +0x16e
testing.runTests(0xc4201f0200, 0x171e1a0, 0x115, 0x115, 0x1762600)
	/usr/local/go/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc420230080, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x2ce
github.com/kata-containers/runtime/cli.runUnitTests(0xc420230080)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/main_test.go:132 +0x39
github.com/kata-containers/runtime/cli.TestMain(0xc420230080)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/main_test.go:173 +0x15c
main.main()
	_testmain.go:690 +0x321

goroutine 20 [syscall]:
os/signal.signal_recv(0x472a91)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f

goroutine 340 [select, locked to thread]:
runtime.gopark(0x10464d8, 0x0, 0x100ae3a, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0xf9
runtime.selectgo(0xc42022bf50, 0xc4201f7200)
	/usr/local/go/src/runtime/select.go:392 +0x11d4
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x19f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 312 [chan receive]:
github.com/kata-containers/runtime/cli.setupSignalHandler.func1(0xc4200a6540)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/main.go:173 +0x93
created by github.com/kata-containers/runtime/cli.setupSignalHandler
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/main.go:171 +0x17c

goroutine 363 [syscall]:
syscall.Syscall(0x1, 0x11, 0xc420400a80, 0xd0, 0xc4204d6900, 0x2102868, 0xc420496ae0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x11, 0xc420400a80, 0xd0, 0x16f, 0x77, 0xc420262601, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1022 +0x70
syscall.Write(0x11, 0xc420400a80, 0xd0, 0x16f, 0x101a988, 0xd29b9c, 0xc4202e0f60)
	/usr/local/go/src/syscall/syscall_unix.go:181 +0x6b
internal/poll.(*FD).Write(0xc4202078b0, 0xc420400a80, 0xd0, 0x16f, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:256 +0x1c2
os.(*File).write(0xc420208538, 0xc420400a80, 0xd0, 0x16f, 0xc4200c216c, 0xc420496cc0, 0x490ea7)
	/usr/local/go/src/os/file_unix.go:243 +0x6e
os.(*File).Write(0xc420208538, 0xc420400a80, 0xd0, 0x16f, 0x16f, 0x0, 0x0)
	/usr/local/go/src/os/file.go:144 +0x8e
github.com/kata-containers/runtime/vendor/github.com/sirupsen/logrus.Entry.log(0xc4200c2140, 0xc4201e66f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4, ...)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/vendor/github.com/sirupsen/logrus/entry.go:117 +0x5e8
github.com/kata-containers/runtime/vendor/github.com/sirupsen/logrus.(*Entry).Info(0xc420206a50, 0xc420496f90, 0x1, 0x1)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/vendor/github.com/sirupsen/logrus/entry.go:144 +0x111
github.com/kata-containers/runtime/cli.createCgroupsFiles(0x10081c7, 0x1, 0x0, 0x0, 0x2102840, 0x0, 0x0, 0x3e8, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/create.go:323 +0xb54
github.com/kata-containers/runtime/cli.create(0x10081c7, 0x1, 0xc4204de8c0, 0x15, 0x100d455, 0x9, 0xc4204de2a0, 0x12, 0x0, 0x0, ...)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/create.go:166 +0x585
github.com/kata-containers/runtime/cli.run(0x10081c7, 0x1, 0xc4204de2c0, 0x15, 0x100d455, 0x9, 0x0, 0x0, 0xc4204de2a0, 0x12, ...)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/run.go:84 +0x17d
github.com/kata-containers/runtime/cli.TestRunContainerDeleteFail(0xc42030a0f0)
	/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime/cli/run_test.go:434 +0x8ba
testing.tRunner(0xc42030a0f0, 0x1044660)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/kata-containers/runtime/cli	13.344s
Makefile:394: recipe for target 'go-test' failed
make: *** [go-test] Error 1
```

**Comment by devimc** [comment]
@chavafg can we close this?

**Comment by chavafg** [comment]
yes, seems like it was a transitory failure, never saw it again.
