### ISSUE TITLE
Yamux tests fail randomly: panic: test timed out after 10s

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#673]
# Description of problem

```
=== RUN   TestSignalBacktrace
--- PASS: TestSignalBacktrace (0.14s)
PASS
coverage: 47.0% of statements
ok  	github.com/kata-containers/agent	6.532s	coverage: 47.0% of statements
INFO: Running 'go test' as current user on package 'github.com/kata-containers/agent/pkg/uevent' with flags '-v -race -timeout 10s'
?   	github.com/kata-containers/agent/pkg/uevent	[no test files]
INFO: Running 'go test' as root user on package 'github.com/kata-containers/agent/pkg/uevent' with flags '-v -race -timeout 10s'
?   	github.com/kata-containers/agent/pkg/uevent	[no test files]
INFO: Running 'go test' as current user on package 'github.com/kata-containers/agent/protocols/client' with flags '-v -race -timeout 10s'
=== RUN   TestNewAgentClient
--- PASS: TestNewAgentClient (1.01s)
=== RUN   TestNewAgentClientWithYamux
--- PASS: TestNewAgentClientWithYamux (1.01s)
PASS
coverage: 81.9% of statements
ok  	github.com/kata-containers/agent/protocols/client	3.035s	coverage: 81.9% of statements
INFO: Running 'go test' as root user on package 'github.com/kata-containers/agent/protocols/client' with flags '-v -race -timeout 10s'
=== RUN   TestNewAgentClient
--- PASS: TestNewAgentClient (1.01s)
=== RUN   TestNewAgentClientWithYamux
coverage: 81.9% of statements
panic: test timed out after 10s

goroutine 82 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0x146
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201c2000, 0xca1582, 0x1b, 0xcbd150, 0xc420071c01)
	/usr/local/go/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc4201c2000)
	/usr/local/go/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc4201c2000, 0xc420071d48)
	/usr/local/go/src/testing/testing.go:777 +0x16e
testing.runTests(0xc4201944c0, 0x1054260, 0x2, 0x2, 0xc4201c0000)
	/usr/local/go/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc4201c0000, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x2ce
main.main()
	_testmain.go:90 +0x325

goroutine 52 [chan receive]:
github.com/kata-containers/agent/protocols/client.TestNewAgentClientWithYamux(0xc4201c21e0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:155 +0x31a
testing.tRunner(0xc4201c21e0, 0xcbd150)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565

goroutine 53 [runnable]:
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*Server).Serve(0xc420001b00, 0xd1d200, 0xc4200c8f20, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/server.go:512 +0x47a
github.com/kata-containers/agent/protocols/client.startMockServer.func1(0xc420276000, 0xd1d680, 0xc4200a4d20, 0x1, 0xc4201c21e0, 0xc420001b00)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:55 +0x9a
created by github.com/kata-containers/agent/protocols/client.startMockServer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:44 +0x23a

goroutine 16 [chan receive]:
github.com/kata-containers/agent/protocols/client.commonDialer(0x4a8177d6d, 0xc4201ee120, 0xd15dc0, 0xc420236660, 0x2, 0x2, 0xd15dc0, 0xc420236660)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:284 +0x127
github.com/kata-containers/agent/protocols/client.vsockDialer(0xc4200243f0, 0xb, 0x4a8177d6d, 0xbeda0ef0f4b8a940, 0x10eef63, 0x1065780, 0x4a8177d6d)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:305 +0x2d8
github.com/kata-containers/agent/vendor/google.golang.org/grpc.WithDialer.func1.1(0xd1e240, 0xc420292660, 0xc4200243f0, 0xb, 0xc420298370, 0x30, 0xc4202983a0, 0xc42028f540)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:293 +0xfe
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.dial(0xd1e240, 0xc420292660, 0xc420062450, 0xc4200243f0, 0xb, 0xc420282150, 0xbc49c0, 0x38, 0xbc49f8)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:112 +0x78
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.newHTTP2Client(0xd1e1c0, 0xc42024e280, 0xc4200243f0, 0xb, 0x0, 0x0, 0xc4200243f0, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:161 +0x159
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.NewClientTransport(0xd1e1c0, 0xc42001e600, 0xc4200243f0, 0xb, 0x0, 0x0, 0xc4200243f0, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/transport.go:510 +0xbe
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc4201e0400, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:965 +0x4f5
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc4201e0400)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:739 +0x3d
created by github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:738 +0x173

goroutine 41 [runnable]:
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.Dial(0x6400000000, 0x1, 0xd26e1, 0xd171a0, 0xc42005df60)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/vsock.go:48 +0xa7
github.com/kata-containers/agent/protocols/client.vsockDialer.func1(0x102a490, 0xc400000001, 0xd26e0, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:300 +0x73
github.com/kata-containers/agent/protocols/client.commonDialer.func1(0xc420288840, 0xc4201ee120, 0xc420298460, 0xc4202888a0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:267 +0xbd
created by github.com/kata-containers/agent/protocols/client.commonDialer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:258 +0xe6

goroutine 30 [runnable]:
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.dialStream(0x6400000000, 0x0, 0x0, 0xd171a0, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/conn_linux.go:47 +0xbe
github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock.Dial(0x6400000000, 0x1, 0xd26e0, 0xd171a0, 0xc42004f760)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/github.com/mdlayher/vsock/vsock.go:49 +0x43
github.com/kata-containers/agent/protocols/client.vsockDialer.func1(0x102a490, 0xc400000001, 0xd26e4, 0x1016690)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:300 +0x73
github.com/kata-containers/agent/protocols/client.commonDialer.func1(0xc420094900, 0xc4202fe140, 0xc420258320, 0xc420094960)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:267 +0xbd
created by github.com/kata-containers/agent/protocols/client.commonDialer
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:258 +0xe6

goroutine 49 [chan receive]:
github.com/kata-containers/agent/protocols/client.commonDialer(0x4a8174640, 0xc4202fe140, 0xd15dc0, 0xc4202365a0, 0x2, 0x2, 0xd15dc0, 0xc4202365a0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:284 +0x127
github.com/kata-containers/agent/protocols/client.vsockDialer(0xc4204fc140, 0xb, 0x4a8174640, 0x4a8176916, 0xc420292420, 0xc4202582d0, 0x477908)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:305 +0x2d8
github.com/kata-containers/agent/protocols/client.agentDialer.func1(0xc4204fc140, 0xb, 0x4a8174640, 0x0, 0x0, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/protocols/client/client.go:185 +0xb4
github.com/kata-containers/agent/vendor/google.golang.org/grpc.WithDialer.func1.1(0xd1e240, 0xc420292420, 0xc4204fc140, 0xb, 0xc4201c8230, 0x30, 0xc4201c8260, 0xc42006f540)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:293 +0xfe
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.dial(0xd1e240, 0xc420292420, 0xc42009f5c0, 0xc4204fc140, 0xb, 0xc4202420a0, 0x0, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:112 +0x78
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.newHTTP2Client(0xd1e1c0, 0xc42024e100, 0xc4204fc140, 0xb, 0x0, 0x0, 0xc4204fc140, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/http2_client.go:161 +0x159
github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport.NewClientTransport(0xd1e1c0, 0xc4200b29c0, 0xc4204fc140, 0xb, 0x0, 0x0, 0xc4204fc140, 0xb, 0xc9927e, 0xd, ...)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/transport/transport.go:510 +0xbe
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc42033c000, 0x0, 0x0)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:965 +0x4f5
github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc42033c000)
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:739 +0x3d
created by github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*addrConn).connect
	/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/clientconn.go:738 +0x173
FAIL	github.com/kata-containers/agent/protocols/client	10.026s
make: *** [Makefile:64: test] Error 1
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash

export GOPATH=$WORKSPACE/go
export GOROOT="/usr/local/go"
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:${PATH}
```

cc @bergwolf

**Comment by devimc** [comment]
The first time I saw this issue was here https://github.com/kata-containers/agent/pull/338#issuecomment-416858845

**Comment by sboeuf** [comment]
@bergwolf PTAL
